import Link from "next/link";
import { requireUser } from "@/lib/auth";

const guides=[
  {number:"01",title:"Entenda o painel",image:"visao-geral.png",text:"Comece pelo resumo da operação. Veja pendências, próximos passos, revisões e o funil antes de abrir uma ficha.",steps:["Confira a faixa de status da operação.","Priorize tarefas e revisões pendentes.","Abra o detalhe que precisa de ação."],href:"/",action:"Abrir painel"},
  {number:"02",title:"Encontre e organize leads",image:"pesquisa.png",text:"Busque empresas, confira a origem dos dados e registre somente informações profissionais que possam ser justificadas.",steps:["Use os filtros para localizar uma empresa.","Confira fonte, setor e contexto.","Abra a ficha para registrar a próxima ação."],href:"/companies",action:"Abrir leads"},
  {number:"03",title:"Importe uma lista com segurança",image:"importacao.png",text:"Use CSV, revise a prévia e resolva possíveis duplicatas antes de confirmar. Dados de exemplo não são gravados automaticamente.",steps:["Envie ou cole o CSV em UTF-8.","Revise linhas inválidas e duplicatas.","Confirme somente as linhas verificadas."],href:"/companies/import",action:"Ver importação"},
  {number:"04",title:"Revise antes de agir",image:"evidencias.png",text:"Evidências, insights e rascunhos entram como pendentes. Confirme a fonte, o contexto e a decisão antes de aprovar.",steps:["Leia a afirmação e sua fonte.","Diferencie fato, hipótese e desconhecido.","Aprove ou rejeite com justificativa."],href:"/research",action:"Abrir revisão"},
  {number:"05",title:"Acompanhe o pipeline",image:"pipeline.png",text:"Atualize o estágio apenas quando houver uma mudança real. Sempre registre o motivo e a próxima ação manual.",steps:["Filtre a campanha ou estágio.","Abra a oportunidade correta.","Registre o motivo da mudança."],href:"/pipeline",action:"Abrir pipeline"},
  {number:"06",title:"Trabalhe com tarefas",image:"tarefas.png",text:"Use tarefas como lembretes internos. Nenhuma tarefa envia mensagem ou confirma uma interação por conta própria.",steps:["Confira o responsável e o vencimento.","Execute a ação manualmente.","Marque o resultado depois de concluir."],href:"/tasks",action:"Abrir tarefas"},
];

export default async function HelpPage(){
  const user=await requireUser(),customer=user.isCustomer;
  return <>
    <section className="help-hero"><div><p className="eyebrow">CENTRAL DE AJUDA</p><h1>Como usar o PhishShield</h1><p className="intro">Um guia visual para transformar contexto em inteligência comercial e próximas ações revisáveis.</p></div><div className="help-hero-actions">{customer?<Link className="button" href="/customer/dashboard">Abrir meu dashboard →</Link>:<Link className="button" href="/">Abrir painel →</Link>}<span>Leitura rápida · 6 etapas</span></div></section>
    <section className="help-rule"><span className="help-rule-icon">!</span><div><strong>Regra principal</strong><p>A plataforma prepara informações e recomenda ações. Ela não envia mensagens, não convida contatos e não executa ações externas automaticamente.</p></div></section>
    <section className="help-flow"><div><p className="eyebrow">VISÃO DO FLUXO</p><h2>Da pesquisa à ação manual</h2></div><div className="help-flow-track"><span>Contexto</span><i>→</i><span>Leads</span><i>→</i><span>Pesquisa</span><i>→</i><span>Revisão</span><i>→</i><span>Próxima ação</span></div></section>
    <section className="help-demo"><div className="help-demo-copy"><p className="eyebrow">FLUXO VISUAL</p><h2>Veja a operação acontecendo</h2><p>Esta demonstração passa pelas principais telas na ordem recomendada. As imagens são capturas reais da aplicação atual.</p><span>Use os atalhos abaixo para abrir cada etapa.</span></div><div className="help-demo-screen" aria-label="Demonstração animada do fluxo da plataforma"><img src="/manual/imagens/visao-geral.png" alt="Painel"/><img src="/manual/imagens/pesquisa.png" alt="Buscar"/><img src="/manual/imagens/evidencias.png" alt="Revisão"/><img src="/manual/imagens/pipeline.png" alt="Pipeline"/><img src="/manual/imagens/tarefas.png" alt="Tarefas"/></div></section>
    <section className="help-section-heading"><div><p className="eyebrow">GUIA PASSO A PASSO</p><h2>Aprenda fazendo</h2></div><p>Use os atalhos de cada etapa para abrir a área correspondente.</p></section>
    <section className="help-step-grid">{guides.map(guide=><article className="help-step" key={guide.number}><div className="help-step-top"><span>{guide.number}</span><span>GUIA PRÁTICO</span></div><a className="help-shot-link" href={`/manual/imagens/${guide.image}`} target="_blank" rel="noopener noreferrer"><img className="help-shot" src={`/manual/imagens/${guide.image}`} alt={`Exemplo visual: ${guide.title}`}/><span>Ampliar screenshot ↗</span></a><div className="help-step-body"><h3>{guide.title}</h3><p>{guide.text}</p><details><summary>Ver passo a passo</summary><ol>{guide.steps.map(step=><li key={step}>{step}</li>)}</ol></details><Link href={guide.href}>{guide.action} →</Link></div></article>)}</section>
    <section className="help-columns"><div className="help-example"><p className="eyebrow">EXEMPLO FICTÍCIO</p><h2>Uma abordagem responsável</h2><div className="example-row"><span>Contexto</span><p>“Atendemos empresas de serviços com equipes pequenas.”</p></div><div className="example-row"><span>Pergunta sugerida</span><p>“Como vocês lidam hoje com esse desafio e quem participa dessa avaliação?”</p></div><div className="example-row"><span>Revisar antes</span><p>Nome, segmento, destinatário e se a afirmação está realmente apoiada por uma fonte.</p></div></div><div className="help-checklist"><p className="eyebrow">ANTES DE CONCLUIR</p><h2>Checklist rápido</h2><ul><li>Fonte e finalidade dos dados estão registradas.</li><li>Hipóteses estão marcadas como hipóteses.</li><li>O próximo passo foi realmente decidido.</li><li>Pedidos de não contato foram respeitados.</li><li>Envios externos continuam manuais.</li></ul></div></section>
    <section className="help-manual"><div><p className="eyebrow">MATERIAL COMPLETO</p><h2>Quer ver todos os exemplos?</h2><p>O manual visual completo reúne as telas implementadas, exemplos de rotina e limites operacionais do produto.</p></div><div className="help-manual-links"><span>Manual HTML e PDF disponíveis na documentação do projeto.</span></div></section>
  </>;
}
