import Link from "next/link";
import { eq } from "drizzle-orm";
import { ApiForm } from "@/components/forms";
import { db } from "@/db";
import { customerMemberships, customerOrganizations, customerProfiles } from "@/db/schema";
import { requireUser } from "@/lib/auth";

const steps = [["Contexto da empresa","Entenda o negócio e o mercado."],["Oferta","Registre produtos, serviços e diferenciais."],["Processo comercial","Mapeie como as vendas acontecem hoje."],["Cliente ideal","Defina quem a empresa quer conquistar."]] as const;
function Field({name,label,value,area=false,placeholder}:{name:string;label:string;value?:string;area?:boolean;placeholder?:string}) { return <label>{label}{area?<textarea name={name} defaultValue={value} placeholder={placeholder} rows={4}/>:<input name={name} defaultValue={value} placeholder={placeholder}/>}</label>; }

export default async function Onboarding({searchParams}:{searchParams:Promise<{step?:string}>}) {
  const user=await requireUser(), membership=await db.query.customerMemberships.findFirst({where:eq(customerMemberships.userId,user.id)});
  if(!membership)return <><h1>Onboarding indisponível</h1><p>Esta conta ainda não está vinculada a uma empresa cliente.</p><Link href="/">Voltar ao início</Link></>;
  const organization=await db.query.customerOrganizations.findFirst({where:eq(customerOrganizations.id,membership.organizationId)}), profile=await db.query.customerProfiles.findFirst({where:eq(customerProfiles.organizationId,membership.organizationId)});
  const requested=Number((await searchParams).step ?? Math.max(1,(organization?.onboardingStep??0)+1)), step=Math.min(4,Math.max(1,Number.isFinite(requested)?requested:1)), answers=profile?.answers??{}, [title,subtitle]=steps[step-1], next=step===4?"/customer/dashboard":"/onboarding?step="+(step+1);
  return <><p className="eyebrow">CONFIGURAÇÃO DA EMPRESA</p><h1>Vamos entender o seu negócio.</h1><p className="intro">Essas informações ajudam o Sales Intelligence a transformar contexto comercial em recomendações úteis. Você pode salvar e completar depois.</p><section className="panel"><div className="actions">{steps.map(([label],index)=><Link key={label} className={index+1===step?"button":""} href={"/onboarding?step="+(index+1)}>{index+1}. {label}</Link>)}</div></section><section className="panel"><p className="eyebrow">ETAPA {step} DE 4</p><h2>{title}</h2><p>{subtitle}</p><ApiForm endpoint="onboarding/profile" label={step===4?"Concluir diagnóstico":"Salvar e continuar"} redirectTo={next}><input type="hidden" name="step" value={step}/>{step===1&&<div className="fields"><Field name="companyDescription" label="O que a empresa faz?" value={answers.companyDescription} area placeholder="Descreva o negócio de forma simples."/><Field name="market" label="Em quais mercados ou segmentos atua?" value={answers.market} area/><Field name="regions" label="Quais regiões atende?" value={answers.regions}/><Field name="companySize" label="Qual o tamanho da equipe?" value={answers.companySize}/></div>}{step===2&&<div className="fields"><Field name="productsServices" label="Quais produtos ou serviços oferece?" value={answers.productsServices} area/><Field name="benefits" label="Quais problemas resolve?" value={answers.benefits} area/><Field name="averageTicket" label="Qual o ticket médio?" value={answers.averageTicket}/><Field name="differentiators" label="Quais são os diferenciais?" value={answers.differentiators} area/><Field name="competitors" label="Quais concorrentes conhece?" value={answers.competitors}/></div>}{step===3&&<div className="fields"><Field name="salesChannels" label="Como os clientes chegam hoje?" value={answers.salesChannels} area/><Field name="salesCycle" label="Quanto tempo dura uma venda?" value={answers.salesCycle}/><Field name="salesTeam" label="Como é a equipe comercial?" value={answers.salesTeam}/><Field name="salesChallenges" label="Quais são os desafios comerciais?" value={answers.salesChallenges} area/><Field name="crm" label="Usa CRM, planilhas ou outra ferramenta?" value={answers.crm}/></div>}{step===4&&<div className="fields"><Field name="targetSegments" label="Quais empresas são clientes ideais?" value={answers.targetSegments} area/><Field name="targetSize" label="Qual porte dessas empresas?" value={answers.targetSize}/><Field name="decisionMakers" label="Quem decide a compra?" value={answers.decisionMakers}/><Field name="customerPainPoints" label="Quais dores você quer resolver?" value={answers.customerPainPoints} area/><Field name="exclusionCriteria" label="Quais perfis não são adequados?" value={answers.exclusionCriteria} area/></div>}</ApiForm></section></>;
}
