import { OpportunityManagement } from "@/components/opportunity-management";
import Link from "next/link";
import { notFound } from "next/navigation";
import { eq,and,desc } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import { activities,campaigns,companies,contacts,opportunities,outreachDrafts,products,tasks,users } from "@/db/schema";
import { requireUser } from "@/lib/auth";
import { canWrite } from "@/lib/security";
import { personaLabels,stageLabels } from "@/lib/outreach/contracts";
import { getEvidence } from "@/lib/research/service";
import { ApiForm } from "@/components/forms";
export default async function OpportunityPage({params}:{params:Promise<{id:string}>}){
  const user=await requireUser(),{id}=await params;if(!z.uuid().safeParse(id).success)notFound();
  const [data]=await db.select({o:opportunities,c:companies,campaign:campaigns,p:products}).from(opportunities).innerJoin(companies,eq(opportunities.companyId,companies.id)).innerJoin(campaigns,eq(opportunities.campaignId,campaigns.id)).innerJoin(products,eq(campaigns.productId,products.id)).where(eq(opportunities.id,id));if(!data)notFound();
  const [people,drafts,taskRows,events,facts,assignees]=await Promise.all([db.select().from(contacts).where(eq(contacts.companyId,data.c.id)),db.select().from(outreachDrafts).where(eq(outreachDrafts.opportunityId,id)).orderBy(desc(outreachDrafts.createdAt)),db.select().from(tasks).where(eq(tasks.opportunityId,id)).orderBy(tasks.dueAt),db.select().from(activities).where(eq(activities.opportunityId,id)).orderBy(desc(activities.happenedAt)).limit(50),getEvidence(data.c.id),db.select({id:users.id,name:users.name,role:users.role}).from(users).where(eq(users.active,true))]);
  const eligible=people.filter(c=>!c.doNotContactAt),approvedFacts=facts.filter(f=>f.type==="public_fact"&&f.status==="approved"&&(!f.expiresAt||f.expiresAt>new Date()));const write=canWrite(user.role),blocked=["do_not_contact","not_fit","lost","won"].includes(data.o.stage);
  return <><Link href={`/companies/${data.c.id}/outreach`}>← Contatos e oportunidades</Link><p className="eyebrow">ABORDAGEM ASSISTIDA</p><h1>{data.c.displayName}</h1><Link className="button" href={`/opportunities/${id}/conversation`}>Conversas e próximos passos →</Link><p>{data.campaign.name} · <span className="badge">{stageLabels[data.o.stage]??data.o.stage}</span></p>{blocked&&<p className="notice">Esta oportunidade está bloqueada para novos contatos.</p>}
    <OpportunityManagement opportunity={data.o} write={write}/>
    {write&&!blocked&&eligible.length>0&&<section className="panel"><h2>Preparar rascunho</h2><p>Templates de discovery com revisão humana. Nada é enviado pela aplicação.</p>{!data.p.approvedClaims.length&&<p className="notice">O catálogo não possui capacidades aprovadas. A abordagem fará perguntas sem prometer funcionalidades.</p>}<ApiForm endpoint={`opportunities/${id}/drafts`} label="Gerar rascunho para revisão"><div className="fields"><label>Destinatário<select name="contactId" defaultValue={data.o.primaryContactId}>{eligible.map(c=><option key={c.id} value={c.id}>{c.name} · {c.title}</option>)}</select></label><label>Persona<select name="persona">{Object.entries(personaLabels).map(([value,label])=><option key={value} value={value}>{label}</option>)}</select></label><label>Evidência para personalização<select name="evidenceId"><option value="">Sem evidência específica — abordagem genérica</option>{approvedFacts.map(f=><option key={f.id} value={f.id}>{f.claim.slice(0,140)}</option>)}</select></label><label>Alegação validada do produto<select name="claimIndex"><option value="">Somente discovery, sem alegação de funcionalidade</option>{data.p.approvedClaims.map((c,i)=><option key={i} value={i}>{c}</option>)}</select></label></div></ApiForm></section>}
    <section className="panel"><h2>Rascunhos</h2>{drafts.map(d=><article className="evidence-card" key={d.id}><Link href={`/drafts/${d.id}`}>{people.find(c=>c.id===d.contactId)?.name} · {d.sentConfirmedAt?"Envio confirmado":d.status==="approved"?"Aprovado":d.status==="rejected"?"Descartado":"Aguardando revisão"} →</Link><p>{d.isGeneric?"Abordagem genérica":"Com evidência específica"} · versão {d.version}</p></article>)}{!drafts.length&&<p>Nenhum rascunho preparado.</p>}</section>
    <section className="panel"><h2>Tarefas de acompanhamento</h2>{taskRows.map(t=><p key={t.id}>{t.dueAt.toLocaleDateString("pt-BR",{timeZone:"UTC"})} · {t.description} · {t.status==="pending"?"Pendente":t.status==="done"?"Concluída":"Cancelada"}</p>)}<Link href="/tasks">Ver tarefas e atualizar situação →</Link>{write&&!blocked&&eligible.length>0&&<details><summary>Agendar tarefa manual</summary><ApiForm endpoint={`opportunities/${id}/tasks`} label="Agendar lembrete"><div className="fields"><label>Contato<select name="contactId" defaultValue={data.o.primaryContactId}>{eligible.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Responsável<select name="assigneeId" defaultValue={user.id}>{assignees.filter(a=>a.role!=="viewer").map(a=><option key={a.id} value={a.id}>{a.name}</option>)}</select></label><label>Data (UTC)<input name="dueAt" type="date" required/></label></div><label>Próxima ação<textarea name="description" required minLength={5} maxLength={1000} rows={2}/></label></ApiForm></details>}</section>
    <section className="panel"><h2>Histórico de atividades</h2><p>Últimas 50 atividades. Cópia e aprovação não são envios.</p>{events.map(e=><p key={e.id}>{e.happenedAt.toLocaleString("pt-BR",{timeZone:"UTC"})} UTC · {e.kind==="manual_sent_confirmed"?"Envio manual confirmado pelo operador":e.kind==="opt_out"?"Pedido de não contato registrado":"Mudança de estágio"}</p>)}</section>
  </>;
}
