import Link from "next/link";
import { count, desc, eq, isNull, sql } from "drizzle-orm";
import { db } from "@/db";
import { activities, aiDailyUsage, companies, contacts, conversationInsights, opportunities, outreachDrafts, tasks, users } from "@/db/schema";
import { stageLabels } from "@/lib/outreach/contracts";

const dateLabel=(date:Date)=>date.toLocaleDateString("pt-BR",{day:"2-digit",month:"short"}).replace(".","");
function Metric({icon,color,title,value,caption}:{icon:string;color:string;title:string;value:React.ReactNode;caption:string}){return <article className="metric-card"><span className={`metric-icon ${color}`}>{icon}</span><p>{title}</p><strong>{value}</strong><small>{caption}</small></article>}
function Empty({children}:{children:React.ReactNode}){return <span className="empty-value">{children}</span>}

export default async function Dashboard(){
  const [leadCount,contactCount,draftCount,pendingTasks,pendingReviews,activityCount,funnel,recentTasks,recentActivities,usage]=await Promise.all([
    db.select({total:count()}).from(companies), db.select({total:count()}).from(contacts), db.select({total:count()}).from(outreachDrafts).where(isNull(outreachDrafts.sentConfirmedAt)), db.select({total:count()}).from(tasks).where(eq(tasks.status,"pending")), db.select({total:count()}).from(conversationInsights).where(eq(conversationInsights.status,"pending")), db.select({total:count()}).from(activities).where(isNull(activities.deletedAt)), db.select({stage:opportunities.stage,total:count()}).from(opportunities).groupBy(opportunities.stage),
    db.select({task:tasks,name:contacts.name,company:companies.displayName}).from(tasks).innerJoin(contacts,eq(tasks.contactId,contacts.id)).innerJoin(opportunities,eq(tasks.opportunityId,opportunities.id)).innerJoin(companies,eq(opportunities.companyId,companies.id)).where(eq(tasks.status,"pending")).orderBy(tasks.dueAt).limit(4),
    db.select({activity:activities,name:contacts.name,company:companies.displayName,author:users.name}).from(activities).leftJoin(contacts,eq(activities.contactId,contacts.id)).innerJoin(opportunities,eq(activities.opportunityId,opportunities.id)).innerJoin(companies,eq(opportunities.companyId,companies.id)).innerJoin(users,eq(activities.authorId,users.id)).where(isNull(activities.deletedAt)).orderBy(desc(activities.happenedAt)).limit(5), db.select({reserved:sql<number>`sum(${aiDailyUsage.reservedMicrousd})`}).from(aiDailyUsage)
  ]);
  const stages=["discovered","researched","qualified","contact_identified","ready_for_review","contacted","replied","meeting","won"];
  const maxFunnel=Math.max(1,...funnel.map(row=>Number(row.total))), qualified=funnel.find(row=>["qualified","contact_identified","ready_for_review"].includes(row.stage)), contactsTotal=Number(contactCount[0]?.total??0), pending=Number(pendingTasks[0]?.total??0), reviews=Number(pendingReviews[0]?.total??0);
  return <>
    <div className="dashboard-heading"><div><p className="eyebrow">PAINEL DE OPERAÇÃO</p><h1>Visão geral</h1><p className="intro">Acompanhe o trabalho comercial e escolha a próxima ação com contexto.</p></div><div className="dashboard-filters"><label>Campanha<select aria-label="Filtrar por campanha"><option>Todas as campanhas</option></select></label><label>Período<select aria-label="Filtrar por período"><option>Últimos 30 dias</option></select></label><button className="filter-button" type="button" aria-label="Filtrar painel">⌯</button></div></div>
    <section className="operation-status" aria-label="Status da operação"><div><span className="status-dot"/> <strong>Operação em andamento</strong><span>Dados sincronizados com o workspace</span></div><div className="status-summary"><span><b>{pending}</b> tarefas pendentes</span><span><b>{reviews}</b> revisões pendentes</span></div></section>
    <div className="metric-grid"><Metric icon="◎" color="blue" title="Leads encontrados" value={Number(leadCount[0]?.total??0)} caption="Empresas cadastradas"/><Metric icon="◇" color="violet" title="Leads qualificados" value={qualified?Number(qualified.total):<Empty>Sem dados</Empty>} caption="Por estágio do pipeline"/><Metric icon="↗" color="green" title="Abordagens registradas" value={Number(activityCount[0]?.total??0)} caption="Registro operacional"/><Metric icon="◷" color="orange" title="Taxa de resposta" value={<Empty>Sem dados</Empty>} caption="Não há métrica disponível"/><Metric icon="◌" color="red" title="Revisões pendentes" value={reviews} caption="Insights aguardando decisão"/><Metric icon="$" color="teal" title="Custo estimado de IA" value={usage[0]?.reserved ? `$ ${(Number(usage[0].reserved)/1000000).toFixed(2)}` : <Empty>Sem dados</Empty>} caption="Uso registrado"/></div>
    <div className="dashboard-columns"><section className="dashboard-panel"><div className="section-heading"><div><p className="eyebrow">PRÓXIMOS PASSOS</p><h2>Próximas ações</h2></div><Link href="/tasks">Ver todas →</Link></div>{recentTasks.length?<div className="action-list">{recentTasks.map(({task,name,company})=><article className="action-item" key={task.id}><span className="action-check">○</span><div><strong>{name}</strong><span>{company} · {task.description}</span></div><time>{dateLabel(task.dueAt)}</time></article>)}</div>:<div className="empty-state"><span>✓</span><p>Nenhuma tarefa pendente no momento.</p><Link href="/pipeline">Abrir pipeline →</Link></div>}</section>
      <section className="dashboard-panel"><div className="section-heading"><div><p className="eyebrow">CONTROLE DE QUALIDADE</p><h2>Aguardando revisão</h2></div><Link href="/outreach">Abrir fila →</Link></div>{Number(draftCount[0]?.total??0)+reviews>0?<div className="review-summary"><div className="review-number">{Number(draftCount[0]?.total??0)+reviews}</div><div><strong>Itens precisam de atenção</strong><p>Revise evidências e rascunhos antes de qualquer ação manual.</p><Link href="/outreach" className="text-link">Ir para revisão →</Link></div></div>:<div className="empty-state"><span>✓</span><p>Nenhuma revisão pendente.</p><Link href="/outreach">Ver abordagens →</Link></div>}</section></div>
    <div className="dashboard-columns lower"><section className="dashboard-panel funnel-panel"><div className="section-heading"><div><p className="eyebrow">PIPELINE COMERCIAL</p><h2>Funil por estágio</h2></div><Link href="/pipeline">Detalhar →</Link></div><div className="funnel-list">{stages.map(stage=>{const total=Number(funnel.find(row=>row.stage===stage)?.total??0);return <div className="funnel-row" key={stage}><span>{stageLabels[stage]??stage}</span><div className="funnel-track"><i style={{width:`${Math.max(total?4:0,total/maxFunnel*100)}%`}}/></div><b>{total}</b></div>})}</div></section>
      <section className="dashboard-panel activity-panel"><div className="section-heading"><div><p className="eyebrow">REGISTRO RECENTE</p><h2>Atividades recentes</h2></div><span className="muted-label">{contactsTotal} contatos</span></div>{recentActivities.length?<div className="activity-list">{recentActivities.map(({activity,name,company,author})=><article className="activity-item" key={activity.id}><span className="activity-dot"/><div><strong>{activity.kind.replaceAll("_"," ")}</strong><span>{name??company} · por {author}</span></div><time>{dateLabel(activity.happenedAt)}</time></article>)}</div>:<div className="empty-state compact"><p>Nenhuma atividade registrada.</p><Link href="/companies">Começar uma pesquisa →</Link></div>}</section></div>
  </>;
}
