"use client";
import Link from "next/link";
import { useRef,useState } from "react";
import { importFields,importFieldLabels,parseCsv } from "@/lib/crm/csv";
import type { getImport } from "@/lib/crm/imports";
type Preview=Awaited<ReturnType<typeof getImport>>;
export function CompanyImport({people,campaigns,ownerId,initial}:{people:{id:string;name:string}[];campaigns:{id:string;name:string}[];ownerId:string;initial?:Preview}){
  const [csv,setCsv]=useState(""),[headers,setHeaders]=useState<string[]>([]),[batch,setBatch]=useState<Preview|null>(initial??null),[error,setError]=useState(""),[pending,setPending]=useState(false),[done,setDone]=useState(initial?.result??null);
  const request=useRef<{body:string;key:string}|null>(null);
  async function post(path:string,body:unknown){const response=await fetch(`/api/v1/${path}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const json=await response.json();if(!response.ok)throw new Error(json.error?.message??"Falha na importação.");return json.data;}
  function inspect(){setError("");try{setHeaders(parseCsv(csv).headers);setBatch(null);setDone(null);}catch(e){setHeaders([]);setError((e as Error).message);}}
  return <>
    {!batch&&<section className="panel"><h2>1. Escolher arquivo</h2><p>CSV em UTF-8, até 200 empresas e 120 mil caracteres. Separador vírgula ou ponto e vírgula; campos entre aspas são aceitos. Cabeçalhos precisam ser únicos.</p><label>Arquivo CSV<input type="file" accept=".csv,text/csv" disabled={pending} onChange={async e=>{const f=e.target.files?.[0];if(!f)return;try{if(f.size>480000)throw new Error("Arquivo excede o limite.");const text=new TextDecoder("utf-8",{fatal:true}).decode(await f.arrayBuffer());setCsv(text);setHeaders([]);setError("");}catch{setError("Arquivo muito grande ou fora de UTF-8.");}}}/></label><label>Conteúdo CSV<textarea rows={6} value={csv} maxLength={120000} onChange={e=>{setCsv(e.target.value);setHeaders([]);}} placeholder={'nome,setor,dominio,cnpj\nEmpresa exemplo,Contabilidade,exemplo.invalid,'}/></label><button onClick={inspect}>Ler colunas</button></section>}
    {!batch&&headers.length>0&&<section className="panel"><h2>2. Mapear e preparar prévia</h2><form onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setPending(true);setError("");try{const mapping=Object.fromEntries(importFields.filter(f=>form.get(`map-${f}`)!=="").map(f=>[f,Number(form.get(`map-${f}`))]));const data={csv,mapping,ownerId:form.get("ownerId"),campaignId:form.get("campaignId"),sourceUrl:form.get("sourceUrl"),permittedBasis:form.get("permittedBasis"),authorization:form.get("authorization")};const body=JSON.stringify(data);if(request.current?.body!==body)request.current={body,key:crypto.randomUUID()};setBatch(await post("companies/import",{...data,requestKey:request.current!.key}));}catch(e){setError((e as Error).message);}finally{setPending(false);}}}>
      <div className="fields">{importFields.map(field=><label key={field}>{importFieldLabels[field]}{["displayName","sector"].includes(field)?" *":""}<select name={`map-${field}`} required={["displayName","sector"].includes(field)} defaultValue={(()=>{const aliases:Record<string,string[]>={displayName:["nome","empresa","displayname"],sector:["setor","sector"],domain:["dominio","domínio","domain"],cnpj:["cnpj"]};const i=headers.findIndex(h=>(aliases[field]??[field.toLowerCase()]).includes(h.toLowerCase()));return i<0?"":String(i);})()}><option value="">Não importar</option>{headers.map((h,i)=><option key={i} value={i}>{h}</option>)}</select></label>)}</div>
      <div className="fields"><label>Responsável pelos novos cadastros<select name="ownerId" defaultValue={ownerId}>{people.map(p=><option key={p.id} value={p.id}>{p.name}</option>)}</select></label><label>Vincular à campanha<select name="campaignId"><option value="">Sem campanha</option>{campaigns.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>URL da origem dos dados<input name="sourceUrl" type="url" required maxLength={2000}/></label></div><label>Permissão de uso verificada<textarea name="permittedBasis" required minLength={10} maxLength={1000} rows={2}/></label><label className="checkbox"><input name="authorization" type="checkbox" value="authorized_import" required/>Tenho autorização para usar estes dados profissionais e conferi sua origem.</label><button disabled={pending}>{pending?"Preparando…":"Gerar prévia"}</button></form></section>}
    {batch&&!done&&<section className="panel"><h2>3. Revisar {batch.rows.length} linhas</h2><p>Nenhuma empresa foi criada ainda. Vincular usa o cadastro existente sem substituir seus dados. Para corrigir uma linha inválida, ajuste o CSV e gere outra prévia.</p><Link href={`/companies/import?batch=${batch.id}`}>Link para retomar esta prévia</Link><form key={batch.id} onSubmit={async e=>{e.preventDefault();const form=new FormData(e.currentTarget);setPending(true);setError("");try{const decisions=batch.rows.map(r=>{const value=String(form.get(`row-${r.line}`));return {line:r.line,action:value.startsWith("link:")?"link":value==="distinct"?"create":value,companyId:value.startsWith("link:")?value.slice(5):undefined,distinct:value==="distinct"};});setDone(await post(`companies/imports/${batch.id}/commit`,{confirmation:form.get("confirmation"),decisions}));}catch(e){setError((e as Error).message);}finally{setPending(false);}}}>
      {batch.rows.map(row=><article className="evidence-card" key={row.line}><h3>Linha {row.line}: {row.data?.displayName??"Dados inválidos"}</h3><p>{row.data?.sector} · {row.data?.domainNormalized??"Sem domínio"} · {row.data?.cnpj??"Sem CNPJ"}</p>{row.errors.map((err,i)=><p className="error" key={i}>{err}</p>)}{row.earlierLines.length>0&&<p className="notice">Possível repetição das linhas {row.earlierLines.join(", ")} deste arquivo.</p>}{row.matches.length>0&&<p className="notice">Há possíveis correspondências no cadastro. CNPJ igual identifica duplicata; domínio/nome exigem revisão.</p>}<label>Decisão da linha {row.line}<select name={`row-${row.line}`} required defaultValue={row.errors.length?"skip":row.matches.length||row.earlierLines.length?"":"create"}><option value="">Escolha após revisar</option>{!row.errors.length&&<><option value="create">Criar nova empresa</option><option value="distinct">Confirmei: empresa distinta com nome/domínio compartilhado</option>{row.matches.map(m=><option key={m.id} value={`link:${m.id}`}>Vincular existente: {m.displayName} · {m.cnpj??m.domainNormalized??m.id}</option>)}</>}<option value="skip">Ignorar esta linha</option></select></label></article>)}
      <label className="checkbox"><input name="confirmation" type="checkbox" value="reviewed_import" required/>Revisei todas as linhas, inclusive as que serão ignoradas, e confirmo a importação.</label><button disabled={pending}>{pending?"Importando…":"Confirmar importação"}</button></form><button className="secondary" disabled={pending} onClick={()=>{setBatch(null);setHeaders([]);setError("");}}>Voltar ao CSV e corrigir</button></section>}
    {done&&<section className="panel"><h2>Importação concluída</h2><p>{done.created} empresas criadas · {done.linked} linhas vinculadas · {done.skipped} linhas ignoradas.</p><Link href={batch?.campaignId?`/companies?campaignId=${batch.campaignId}`:"/companies"}>Ver empresas →</Link></section>}
    {error&&<p className="error" role="alert">{error}</p>}
  </>;
}
