"use client";
import { useState } from "react";
import { useRouter } from "next/navigation";
import { maskSensitive } from "@/lib/conversations/contracts";
export function ConversationEntry({opportunityId,contacts,initialKey}:{opportunityId:string;contacts:{id:string;name:string}[];initialKey:string}){
  const [body,setBody]=useState(""),[message,setMessage]=useState(""),[pending,setPending]=useState(false),[key,setKey]=useState(initialKey);const router=useRouter();
  return <form onSubmit={async event=>{event.preventDefault();const data=Object.fromEntries(new FormData(event.currentTarget));setPending(true);setMessage("");try{const response=await fetch("/api/v1/activities",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...data,body:maskSensitive(body),happenedAt:new Date(String(data.happenedAt)).toISOString(),opportunityId,requestKey:key})});const json=await response.json();if(!response.ok){setMessage(json.error.message);return;}setBody("");setKey(crypto.randomUUID());setMessage("Conversa registrada. Revise os insights antes de alterar a ficha ou o estágio.");router.refresh();}catch{setMessage("Falha ao salvar. Verifique a data e tente novamente.");}finally{setPending(false);}}}>
    <div className="fields"><label>Contato<select name="contactId" required>{contacts.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Tipo de registro<select name="kind"><option value="inbound_message">Mensagem recebida do contato (texto original)</option><option value="outbound_note">Nota sobre mensagem enviada pelo operador</option><option value="conversation_note">Resumo / nota do operador</option></select></label><label>Canal<select name="channel"><option value="linkedin">LinkedIn</option><option value="email">E-mail</option><option value="phone">Telefone</option><option value="meeting">Reunião</option><option value="other">Outro</option></select></label><label>Data e hora da interação (seu fuso local)<input name="happenedAt" type="datetime-local" required/></label></div>
    <label>Mensagem ou nota<textarea name="body" rows={6} value={body} onChange={e=>setBody(e.target.value)} required minLength={3} maxLength={8000}/></label><details open={maskSensitive(body)!==body}><summary>Prévia do texto que será salvo</summary><p className="preserve">{maskSensitive(body)||"Digite o conteúdo acima."}</p></details>
    <p>O mascaramento cobre padrões comuns de CPF, números longos, e-mail e segredos rotulados. Revise outros dados sensíveis manualmente. Notas do operador não são tratadas como falas literais do contato.</p>
    <label>Fundamento / permissão para armazenar esta conversa<textarea name="permittedBasis" rows={2} minLength={10} maxLength={1000} required/></label><label className="checkbox"><input type="checkbox" name="attestation" value="authorized_and_redacted" required/>Tenho autorização/base adequada para registrar este conteúdo e revisei a remoção dos dados sensíveis desnecessários.</label><p role="status">{message}</p><button disabled={pending}>{pending?"Salvando…":"Registrar conversa"}</button>
  </form>;
}
