"use client";

import Link from "next/link";
import { useState } from "react";
import { parseCsv } from "@/lib/crm/csv";

const fields = ["companyName","domain","contactName","contactTitle","contactEmail","nextAction","notes"] as const;
const labels:Record<string,string> = {companyName:"Empresa",domain:"Domínio",contactName:"Contato",contactTitle:"Cargo",contactEmail:"E-mail",nextAction:"Próxima ação",notes:"Notas"};
type Row = Record<string,string>;

export function CustomerLeadImport() {
  const [csv,setCsv] = useState(""),[headers,setHeaders] = useState<string[]>([]),[rows,setRows] = useState<(Row & {line:number;duplicate:boolean})[]>([]),[error,setError] = useState(""),[pending,setPending] = useState(false),[result,setResult] = useState<{created:number;skipped:number}|null>(null);
  function inspect() { setError(""); setRows([]); setResult(null); try { setHeaders(parseCsv(csv).headers); } catch (e) { setHeaders([]); setError(e instanceof Error ? e.message : "CSV inválido."); } }
  function buildRows(form:HTMLFormElement) { const parsed=parseCsv(csv), data=new FormData(form), mapping=Object.fromEntries(fields.map(field=>[field,Number(data.get("map-"+field))])); return parsed.rows.map(row=>Object.fromEntries(fields.map(field=>[field,mapping[field]>=0 ? row.cells[mapping[field]]?.trim() ?? "" : ""]))); }
  async function preview(event:React.FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); setError(""); try { const response=await fetch("/api/v1/customer/leads/import/preview",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows:buildRows(event.currentTarget)})}); const json=await response.json(); if(!response.ok)throw Error(json.error?.message??"Não foi possível gerar a prévia."); setRows(json.data.rows); } catch(e) { setError(e instanceof Error?e.message:"Falha na importação."); } finally { setPending(false); } }
  async function commit() { setPending(true); setError(""); try { const response=await fetch("/api/v1/customer/leads/import/commit",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({rows:rows.map(({line,duplicate,...row})=>row),confirmation:"confirmed"})}); const json=await response.json(); if(!response.ok)throw Error(json.error?.message??"Não foi possível importar."); setResult(json.data); setRows([]); } catch(e) { setError(e instanceof Error?e.message:"Falha na importação."); } finally { setPending(false); } }
  return <>{!result&&<section className="panel"><h2>1. Escolher arquivo</h2><p>CSV UTF-8, até 200 leads. Cabeçalhos aceitos: empresa, domínio, contato, cargo, e-mail, próxima ação e notas.</p><label>Arquivo CSV<input type="file" accept=".csv,text/csv" onChange={async event=>{const file=event.target.files?.[0];if(!file)return;try{setCsv(new TextDecoder("utf-8",{fatal:true}).decode(await file.arrayBuffer()));setHeaders([]);setRows([]);setError("");}catch{setError("Arquivo fora de UTF-8.");}}}/></label><label>Ou cole o conteúdo<textarea rows={6} value={csv} onChange={event=>{setCsv(event.target.value);setHeaders([]);setRows([])}} placeholder={"empresa,dominio,contato,email\nEmpresa exemplo,exemplo.com,Ana,ana@exemplo.com"}/></label><button onClick={inspect}>Ler colunas</button></section>}
    {headers.length>0&&!rows.length&&!result&&<section className="panel"><h2>2. Mapear colunas</h2><form onSubmit={preview}><div className="fields">{fields.map(field=><label key={field}>{labels[field]}{field==="companyName"&&" *"}<select name={"map-"+field} required={field==="companyName"} defaultValue={headers.findIndex(header=>header.toLowerCase().normalize("NFD").replace(/[\u0300-\u036f]/g,"").includes(field==="companyName"?"empresa":field==="contactEmail"?"email":field.toLowerCase()))}><option value="-1">Não importar</option>{headers.map((header,index)=><option value={index} key={index}>{header}</option>)}</select></label>)}</div><button disabled={pending}>{pending?"Preparando…":"Gerar prévia"}</button></form></section>}
    {rows.length>0&&!result&&<section className="panel"><h2>3. Revisar importação</h2><p>{rows.length} linhas encontradas · {rows.filter(row=>row.duplicate).length} possíveis duplicados serão ignorados.</p>{rows.map(row=><article className="evidence-card" key={row.line}><strong>Linha {row.line}: {row.companyName}</strong>{row.contactName&&<p>{row.contactName} · {row.contactEmail}</p>}{row.duplicate&&<p className="notice">Possível duplicado no cadastro desta empresa.</p>}</article>)}<button disabled={pending} onClick={commit}>{pending?"Importando…":"Confirmar importação"}</button><p><button className="secondary" onClick={()=>setRows([])}>Voltar ao mapeamento</button></p></section>}
    {result&&<section className="panel"><h2>Importação concluída</h2><p>{result.created} leads criados · {result.skipped} duplicados ignorados.</p><Link className="button" href="/customer/leads">Ver leads →</Link></section>}
    {error&&<p className="error" role="alert">{error}</p>}</>;
}
