"use client";
import Link from "next/link";
import { usePathname } from "next/navigation";
import { useEffect, useState } from "react";

type Item={href:string;label:string;icon:string};
const customerItems:Item[]=[{href:"/help",label:"Como usar",icon:"?"},{href:"/customer/dashboard",label:"Dashboard",icon:"⌂"},{href:"/onboarding",label:"Configurar empresa",icon:"◇"},{href:"/team",label:"Equipe",icon:"♧"},{href:"/customer/leads",label:"Leads e oportunidades",icon:"◎"},{href:"/customer/tasks",label:"Tarefas",icon:"✓"},{href:"/insights",label:"Insights comerciais",icon:"◒"}];
const operationItems:Item[]=[{href:"/",label:"Painel",icon:"⌂"},{href:"/research",label:"Buscar",icon:"⌕"},{href:"/companies",label:"Leads",icon:"◎"},{href:"/outreach",label:"Revisão",icon:"◌"},{href:"/tasks",label:"Tarefas",icon:"✓"},{href:"/help",label:"Como usar",icon:"?"}];
const adminItems:Item[]=[{href:"/admin/ai",label:"Configurações",icon:"⚙"},{href:"/team",label:"Usuários",icon:"♧"},{href:"/admin",label:"Auditoria",icon:"▣"}];
function isActive(pathname:string,href:string){return pathname===href||(href!=="/"&&pathname.startsWith(href+"/"));}
function NavGroup({title,items,collapsed,onNavigate}:{title:string;items:Item[];collapsed:boolean;onNavigate:()=>void}){const pathname=usePathname();return <section className="nav-group" style={{minWidth:0}}><p className="nav-label nav-group-label" style={collapsed?{display:"none"}:undefined}>{title}</p>{items.map(item=>{const active=isActive(pathname,item.href);return <Link key={item.href} title={collapsed?item.label:undefined} className={active?"nav-link active":"nav-link"} aria-current={active?"page":undefined} href={item.href} onClick={onNavigate} style={{minWidth:0}}><span className="nav-icon" aria-hidden="true">{item.icon}</span><span className="nav-text" style={{flex:1,minWidth:0,overflow:"hidden",textOverflow:"ellipsis",whiteSpace:"nowrap",paddingRight:4}}>{item.label}</span></Link>})}</section>}
export function WorkspaceNavigation({customer,owner}:{customer:boolean;owner:boolean}){const[collapsed,setCollapsed]=useState(false);const[mobileOpen,setMobileOpen]=useState(false);useEffect(()=>{setCollapsed(window.localStorage.getItem("phishshield.sidebar.collapsed")==="true")},[]);function toggle(){const next=!collapsed;setCollapsed(next);window.localStorage.setItem("phishshield.sidebar.collapsed",String(next));}function close(){setMobileOpen(false)}return <><button className="sidebar-toggle" type="button" aria-label={collapsed?"Expandir menu":"Recolher menu"} onClick={toggle}>{collapsed?"→":"←"}</button><button className="mobile-menu-toggle" type="button" aria-label="Abrir menu" aria-expanded={mobileOpen} onClick={()=>setMobileOpen(!mobileOpen)}>☰ <span>Menu</span></button>{mobileOpen&&<button className="mobile-overlay" type="button" aria-label="Fechar menu" onClick={close} style={{background:"#0008",border:0,inset:0,position:"fixed",zIndex:3}}/>}<nav className={`workspace-nav ${collapsed?"is-collapsed":""} ${mobileOpen?"is-mobile-open":""}`} aria-label="Navegação principal">{customer?<NavGroup title="Workspace" items={customerItems} collapsed={collapsed} onNavigate={close}/>:<><NavGroup title="Operação" items={operationItems} collapsed={collapsed} onNavigate={close}/>{owner&&<NavGroup title="Administração" items={adminItems} collapsed={collapsed} onNavigate={close}/>}</>}</nav></>}
export function WorkspaceLocation({customer}:{customer:boolean}){const pathname=usePathname();const current=customer?(pathname==="/customer/dashboard"?"Dashboard":pathname.startsWith("/customer/leads")?"Leads e oportunidades":pathname==="/customer/tasks"?"Tarefas":pathname==="/team"?"Equipe":"Área de trabalho"):(pathname==="/"?"Painel":pathname.startsWith("/research")?"Buscar":pathname.startsWith("/outreach")?"Revisão":pathname.startsWith("/companies")?"Leads":pathname.startsWith("/tasks")?"Tarefas":pathname.startsWith("/admin")?"Administração":"Área de trabalho");return <span>Você está em: {current}</span>}
