import Link from "next/link";
import { randomUUID } from "node:crypto";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import { contacts,opportunities,outreachDrafts,products } from "@/db/schema";
import { requireUser } from "@/lib/auth";
import { canWrite } from "@/lib/security";
import { personaLabels } from "@/lib/outreach/contracts";
import { getEvidence } from "@/lib/research/service";
import { ApiForm } from "@/components/forms";
import { DraftCopy } from "@/components/draft-copy";
import { WritingForm } from "@/components/writing-form";
import { defaultWritingProvider,publicWritingConfig } from "@/lib/writing/provider";
export default async function DraftPage({params}:{params:Promise<{id:string}>}){
  const user=await requireUser(),{id}=await params;if(!z.uuid().safeParse(id).success)notFound();
  const [data]=await db.select({d:outreachDrafts,c:contacts,o:opportunities,p:products}).from(outreachDrafts).innerJoin(contacts,eq(outreachDrafts.contactId,contacts.id)).innerJoin(opportunities,eq(outreachDrafts.opportunityId,opportunities.id)).innerJoin(products,eq(outreachDrafts.productId,products.id)).where(eq(outreachDrafts.id,id));if(!data)notFound();const {d,c,o,p}=data;
  const facts=await getEvidence(o.companyId);const stale=p.version!==d.productVersion||d.evidenceSnapshot.some(s=>!facts.some(f=>f.id===s.id&&f.version===s.version&&f.status==="approved"&&f.type==="public_fact"&&(!f.expiresAt||f.expiresAt>new Date())));
  const blocked=!!c.doNotContactAt||["do_not_contact","not_fit","lost","won"].includes(o.stage),write=canWrite(user.role),mutable=write&&!blocked&&!d.sentConfirmedAt&&!stale;
  return <><Link href={`/opportunities/${o.id}`}>← Oportunidade</Link><p className="eyebrow">REVISÃO DE ABORDAGEM</p><h1>Mensagem para {c.name}</h1><p>LinkedIn · {personaLabels[d.persona as keyof typeof personaLabels]} · versão {d.version}</p><section className="notice"><strong>{d.isGeneric?"Abordagem genérica — sem evidência específica":"Abordagem com evidência pública"}</strong><p>{d.rationale}</p></section>{blocked&&<p className="error">Opt-out ou oportunidade encerrada: não contatar. Não use textos copiados anteriormente.</p>}{stale&&!d.sentConfirmedAt&&<p className="error">Catálogo ou evidência alterados/expirados. Gere um novo rascunho.</p>}
    <section className="panel"><h2>{d.sentConfirmedAt?"Envio manual confirmado":d.status==="approved"?"Texto aprovado":d.status==="rejected"?"Rascunho descartado":"Texto para revisão"}</h2><p className="preserve">{d.message}</p><p>Catálogo: {d.productSnapshot.name}, versão {d.productVersion}. {d.generation?`Texto gerado por ${d.generation.provider === "claude" ? "Claude" : "GPT"} (${d.generation.model}). ${d.editedBy ? "Editado depois pelo operador." : "Requer conferência humana."}`:d.editedBy?"Texto editado pelo operador; alegações exigem conferência humana.":"Template determinístico; sem IA."}</p><p>{d.copiedAt?`Cópia registrada em ${d.copiedAt.toLocaleString("pt-BR",{timeZone:"UTC"})} UTC.`:"Nenhuma cópia registrada."} {d.sentConfirmedAt?`Envio confirmado em ${d.sentConfirmedAt.toLocaleString("pt-BR",{timeZone:"UTC"})} UTC.`:"Nenhum envio confirmado."}</p></section>
    <section className="panel"><h2>Base para revisão</h2><h3>Alegações permitidas na versão utilizada</h3>{d.productSnapshot.approvedClaims.length?<ul>{d.productSnapshot.approvedClaims.map(s=><li key={s}>{s}</li>)}</ul>:<p>Nenhuma capacidade técnica validada. Não prometer funcionalidades.</p>}<h3>Alegações proibidas</h3><ul>{d.productSnapshot.prohibitedClaims.map(s=><li key={s}>{s}</li>)}</ul><h3>Evidências utilizadas</h3>{d.evidenceSnapshot.map(s=><p key={s.id}>{s.claim} · {new Date(s.observedAt).toLocaleDateString("pt-BR",{timeZone:"UTC"})} · <a href={s.sourceUrl} target="_blank" rel="noopener noreferrer">Ver fonte ↗</a></p>)}{!d.evidenceSnapshot.length&&<p>Nenhuma. A mensagem não presume dores ou tecnologias desta empresa.</p>}</section>
    {mutable&&<section className="panel"><h2>Redigir com IA</h2><p>Gere uma abordagem, resposta ou follow-up com base no rascunho. O novo texto substitui o atual e remove aprovação e registro de cópia. Revise antes de usar.</p><WritingForm key={`writing-${d.version}`} id={id} version={d.version} providers={publicWritingConfig()} defaultProvider={defaultWritingProvider()}/></section>}
    {mutable&&<section className="panel"><h2>Revisar e preparar</h2><details><summary>Editar texto</summary><p>Salvar qualquer edição remove aprovação e registro de cópia. Revise novamente antes de usar.</p><ApiForm key={`edit-${d.version}`} endpoint={`drafts/${id}/edit`} label="Salvar edição e revisar novamente"><input type="hidden" name="version" value={d.version}/><label>Mensagem<textarea name="message" required minLength={10} maxLength={6000} rows={10} defaultValue={d.message}/></label></ApiForm></details>{d.status==="draft"&&<ApiForm endpoint={`drafts/${id}/approve`} label="Aprovar texto"><input type="hidden" name="version" value={d.version}/><label className="checkbox"><input name="attestation" type="checkbox" value="reviewed" required/>Conferi destinatário, fontes, incertezas e alegações. O texto não promete capacidades fora do catálogo nem afirma incidentes sem evidência.</label></ApiForm>}{d.status==="approved"&&<DraftCopy id={id} version={d.version}/>}</section>}
    {mutable&&d.status==="approved"&&<section className="panel"><h2>Confirmar envio manual</h2><p>Envie pessoalmente pelo LinkedIn e só depois registre aqui. Esta ação não abre nem envia mensagens ao LinkedIn.</p>{c.professionalUrl&&<a href={c.professionalUrl} target="_blank" rel="noopener noreferrer">Abrir perfil profissional ↗</a>}<ApiForm endpoint={`drafts/${id}/confirm-sent`} label="Confirmar que enviei manualmente"><input type="hidden" name="version" value={d.version}/><input type="hidden" name="requestKey" value={randomUUID()}/><label className="checkbox"><input type="checkbox" name="confirmation" value="sent_manually" required/>Confirmo que enviei este texto para este contato, manualmente.</label><div className="fields"><label>Próxima ação<select name="createFollowUp"><option value="true">Criar lembrete para revisar resposta</option><option value="false">Não criar lembrete agora</option></select></label><label>Revisar em quantos dias?<input name="followUpDays" type="number" min={1} max={60} defaultValue={7} required/></label></div></ApiForm></section>}
    {write&&!d.sentConfirmedAt&&d.status!=="rejected"&&<section className="panel"><ApiForm endpoint={`drafts/${id}/reject`} label="Descartar rascunho"><input type="hidden" name="version" value={d.version}/></ApiForm></section>}
  </>;
}
