import "dotenv/config";
import assert from "node:assert/strict";
import { mkdir } from "node:fs/promises";
import { chromium,type Browser } from "playwright";
import { eq,or,sql } from "drizzle-orm";
import { db,pool } from "../src/db";
import { auditEvents,companies,contacts,evidence,opportunities,sources } from "../src/db/schema";
const origin=process.env.APP_ORIGIN!;let browser:Browser|undefined,companyId="";
async function main(){
  if(process.env.NODE_ENV==="production"||!["localhost","127.0.0.1"].includes(new URL(origin).hostname))throw new Error("Teste apenas local.");
  browser=await chromium.launch({channel:process.env.TEST_BROWSER_CHANNEL??"msedge",headless:true});const context=await browser.newContext({viewport:{width:1365,height:950}});const external:string[]=[];await context.route("**/*",route=>{const url=new URL(route.request().url());if(url.origin!==origin){external.push(url.hostname);return route.abort();}return route.continue();});
  const page=await context.newPage();const errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.goto(`${origin}/login`);await page.getByLabel("E-mail profissional").fill("operator@demo.invalid");await page.getByLabel("Senha",{exact:true}).fill(process.env.SEED_PASSWORD!);await page.getByRole("button",{name:"Entrar",exact:true}).click();await page.waitForURL(origin+"/");
  async function post(path:string,data:unknown){const r=await context.request.post(`${origin}/api/v1/${path}`,{headers:{origin},data});assert.ok(r.ok(),`${path}: ${r.status()}`);return (await r.json()).data;}
  const company=await post("companies",{displayName:"Contabilidade fictícia — teste de conversa",sector:"Contabilidade"});companyId=company.id;const contact=await post(`companies/${companyId}/contacts`,{name:"Marina Fictícia",title:"Sócia",roleCategory:"owner",sourceUrl:"https://example.invalid",permittedBasis:"Fixture de teste autorizado",purpose:"Validar formulário local de conversas"});const campaign=(await (await context.request.get(`${origin}/api/v1/campaigns`)).json()).data[0];const o=await post("opportunities",{companyId,campaignId:campaign.id,primaryContactId:contact.id});
  const hypothesis=await post(`companies/${companyId}/evidence`,{type:"inference",claim:"Possível problema recorrente com mensagens suspeitas",observedAt:"2026-01-01"});await post(`companies/${companyId}/evidence/${hypothesis.id}/review`,{version:1,status:"approved",note:"Hipótese para teste"});
  await page.goto(`${origin}/opportunities/${o.id}/conversation`);await page.getByLabel("Data e hora da interação (seu fuso local)").fill("2026-01-02T10:00");await page.getByLabel("Mensagem ou nota",{exact:true}).fill("Não temos problemas com mensagens suspeitas. CPF 123.456.789-00");await page.getByLabel("Fundamento / permissão para armazenar esta conversa").fill("Registro fictício autorizado para teste");await page.getByLabel(/Tenho autorização/).check();const saved=page.waitForResponse(r=>r.url().endsWith("/api/v1/activities")&&r.request().method()==="POST");await page.getByRole("button",{name:"Registrar conversa",exact:true}).click();const activity=(await (await saved).json()).data;assert.ok(activity.id);assert.doesNotMatch(activity.body,/123.456.789/);
  const article=page.locator(`#activity-${activity.id}`);await article.getByText("Analisar mensagem",{exact:true}).click();const extracted=page.waitForResponse(r=>r.url().endsWith(`/activities/${activity.id}/extract-insights`));await article.getByRole("button",{name:"Extrair sugestões para revisar"}).click();assert.equal((await extracted).status(),200);
  const detail=(await (await context.request.get(`${origin}/api/v1/opportunities/${o.id}/conversation`)).json()).data;const insight=detail.insights.find((i:{kind:string})=>i.kind==="contradiction");assert.ok(insight);let card=page.locator(`#insight-${insight.id}`);await card.getByText("Editar interpretação",{exact:true}).click();await card.getByLabel("Natureza da interpretação").selectOption("explicit");const edited=page.waitForResponse(r=>r.url().endsWith(`/conversation-insights/${insight.id}/edit`));await card.getByRole("button",{name:"Salvar interpretação corrigida"}).click();assert.equal((await edited).status(),200);
  await page.reload();card=page.locator(`#insight-${insight.id}`);await card.getByText("Revisar interpretação",{exact:true}).click();await card.getByLabel("Justificativa",{exact:true}).fill("Negação literal confirmada no texto");await card.getByLabel("Hipótese negada por este trecho (opcional)").selectOption(hypothesis.id);const reviewed=page.waitForResponse(r=>r.url().endsWith(`/conversation-insights/${insight.id}/review`));await card.getByRole("button",{name:"Registrar revisão do insight"}).click();assert.equal((await reviewed).status(),200);await card.getByRole("link",{name:/Declaração revisada publicada/}).waitFor();
  await page.evaluate(()=>window.scrollTo(0,0));await mkdir("test-results",{recursive:true});await page.screenshot({path:"test-results/etapa-4-conversa-desktop.png"});await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await page.screenshot({path:"test-results/etapa-4-conversa-mobile.png"});
  await page.goto(`${origin}/companies/${companyId}`);await page.getByText("Declarado pelo contato",{exact:true}).waitFor();assert.equal((await db.select().from(evidence).where(eq(evidence.id,hypothesis.id)))[0].status,"rejected");assert.equal((await db.select().from(opportunities).where(eq(opportunities.id,o.id)))[0].stage,"contact_identified");assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await post("auth/logout",{});
  console.log("Edge etapa 4 aprovado: registro com mascaramento, extração local, edição/revisão, vínculo de negação, declaração na ficha, pipeline inalterado e layout móvel. Nenhuma requisição externa.");
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();if(companyId){await db.delete(auditEvents).where(or(eq(auditEvents.entityId,companyId),sql`${auditEvents.metadata}->>'companyId' = ${companyId}`));await db.delete(evidence).where(eq(evidence.companyId,companyId));await db.delete(opportunities).where(eq(opportunities.companyId,companyId));await db.delete(contacts).where(eq(contacts.companyId,companyId));await db.delete(sources).where(eq(sources.companyId,companyId));await db.delete(companies).where(eq(companies.id,companyId));}await pool.end();});
