import "dotenv/config";
import assert from "node:assert/strict";
import { randomUUID } from "node:crypto";
import { mkdir } from "node:fs/promises";
import { chromium,type Browser } from "playwright";
import { eq,inArray,or,sql } from "drizzle-orm";
import { db,pool } from "../src/db";
import { auditEvents,campaigns,companies,companyImports,contacts,opportunities } from "../src/db/schema";
const origin=process.env.APP_ORIGIN!,prefix=`Browser CRM ${randomUUID()}`;let browser:Browser|undefined,campaignId="",batchId="";const companyIds:string[]=[];
async function main(){
  if(process.env.NODE_ENV==="production"||!["127.0.0.1","localhost"].includes(new URL(origin).hostname))throw new Error("Somente ambiente local.");
  browser=await chromium.launch({channel:process.env.TEST_BROWSER_CHANNEL??"msedge",headless:true});const context=await browser.newContext({viewport:{width:1440,height:1000}}),external:string[]=[];
  await context.route("**/*",route=>{if(new URL(route.request().url()).origin!==origin){external.push(route.request().url());return route.abort();}return route.continue();});
  const page=await context.newPage(),errors:string[]=[];page.on("pageerror",e=>errors.push(e.message));await page.goto(origin+"/login");await page.getByLabel("E-mail profissional").fill("operator@demo.invalid");await page.getByLabel("Senha",{exact:true}).fill(process.env.SEED_PASSWORD!);await page.getByRole("button",{name:"Entrar",exact:true}).click();await page.waitForURL(origin+"/");
  async function post(path:string,data:unknown){const r=await context.request.post(`${origin}/api/v1/${path}`,{headers:{origin},data});assert.ok(r.ok(),`${path}: ${r.status()}`);return (await r.json()).data;}
  const product=(await (await context.request.get(origin+"/api/v1/products")).json()).data[0];const campaign=await post("campaigns",{name:prefix,productId:product.id,sector:"Contabilidade",employeeMin:5,employeeMax:50});campaignId=campaign.id;
  await page.goto(origin+"/companies/import");await page.getByLabel("Conteúdo CSV").fill(`nome,setor,dominio,cnpj\n${prefix} única,Contabilidade,browser-${campaignId}.invalid,\n${prefix} duplicada,Contabilidade,browser-${campaignId}.invalid,\n${prefix} inválida,Contabilidade,,123`);await page.getByRole("button",{name:"Ler colunas",exact:true}).click();await page.getByRole("heading",{name:"2. Mapear e preparar prévia",exact:true}).waitFor({timeout:5000}).catch(async e=>{console.error(await page.locator("main").innerText());console.error(errors);throw e;});await page.locator('select[name="campaignId"]').selectOption(campaignId);await page.getByLabel("URL da origem dos dados").fill("https://example.invalid/fixture");await page.getByLabel("Permissão de uso verificada").fill("Dados fictícios autorizados para teste local");await page.getByLabel(/Tenho autorização para usar/).check();
  const previewResponse=page.waitForResponse(r=>r.url().endsWith("/companies/import")&&r.request().method()==="POST");await page.getByRole("button",{name:"Gerar prévia",exact:true}).click();const preview=(await (await previewResponse).json()).data;assert.ok(preview?.id);batchId=preview.id;
  await page.getByRole("heading",{name:"3. Revisar 3 linhas",exact:true}).waitFor();assert.equal(await page.locator('select[name="row-3"]').inputValue(),"");await page.locator('select[name="row-3"]').selectOption("skip");assert.equal(await page.locator('select[name="row-4"]').inputValue(),"skip");await mkdir("test-results",{recursive:true});await page.screenshot({path:"test-results/etapa-1-previa-desktop.png",fullPage:true});
  await page.getByLabel(/Revisei todas as linhas/).check();const commitResponse=page.waitForResponse(r=>r.url().endsWith(`/imports/${batchId}/commit`));await page.getByRole("button",{name:"Confirmar importação",exact:true}).click();const imported=(await (await commitResponse).json()).data;assert.equal(imported.created,1);companyIds.push(...imported.companyIds);await page.getByRole("heading",{name:"Importação concluída",exact:true}).waitFor();
  await page.goto(origin+"/companies");await page.getByLabel("Buscar",{exact:true}).fill(prefix);await page.getByRole("button",{name:"Aplicar filtros",exact:true}).click();await page.waitForURL(/q=/);assert.equal(await page.locator("tbody tr").count(),1);
  const companyId=companyIds[0];await page.goto(`${origin}/companies/${companyId}/manage`);await page.getByLabel("Cidade",{exact:true}).fill("São Paulo");await page.getByLabel("UF",{exact:true}).fill("SP");const editResponse=page.waitForResponse(r=>r.url().endsWith(`/companies/${companyId}/edit`));await page.getByRole("button",{name:"Salvar cadastro",exact:true}).click();assert.equal((await editResponse).status(),200);
  const person=await post(`companies/${companyId}/contacts`,{name:"Pessoa Fictícia",title:"Sócia",roleCategory:"owner",sourceUrl:"https://example.invalid/fixture",permittedBasis:"Dados fictícios para teste",purpose:"Teste local de pipeline e histórico"});const deal=await post("opportunities",{companyId,campaignId,primaryContactId:person.id});
  await page.goto(`${origin}/pipeline?campaignId=${campaignId}`);await page.getByText("Mover oportunidade",{exact:true}).click();await page.locator('.pipeline-board select[name="stage"]').selectOption("meeting");await page.getByLabel("Motivo da mudança",{exact:true}).fill("Reunião fictícia confirmada pelo operador");await page.getByLabel(/Revisei a mudança e o motivo/).check();const moveResponse=page.waitForResponse(r=>r.url().endsWith(`/opportunities/${deal.id}/stage`));await page.getByRole("button",{name:"Salvar estágio",exact:true}).click();assert.equal((await moveResponse).status(),200);
  await page.reload();const meeting=page.locator(".pipeline-column").filter({has:page.getByRole("heading",{name:/^Reunião/})});assert.equal(await meeting.getByRole("link",{name:`${prefix} única`,exact:true}).count(),1);await page.screenshot({path:"test-results/etapa-1-pipeline-desktop.png",fullPage:true});
  await page.setViewportSize({width:390,height:844});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);await page.screenshot({path:"test-results/etapa-1-pipeline-mobile.png",fullPage:true});
  await page.goto(`${origin}/opportunities/${deal.id}/history`);await page.getByText("Motivo: Reunião fictícia confirmada pelo operador",{exact:true}).waitFor();assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth),true);
  assert.deepEqual(errors,[]);assert.deepEqual(external,[]);await post("auth/logout",{});console.log("Edge etapa 1 aprovado: mapeamento/prévia, decisões, importação, busca, edição, movimentação do pipeline, histórico e layout móvel; nenhuma chamada externa.");
}
main().catch(e=>{console.error(e);process.exitCode=1;}).finally(async()=>{await browser?.close();if(batchId)await db.delete(companyImports).where(eq(companyImports.id,batchId));if(companyIds.length){await db.delete(auditEvents).where(or(sql`${auditEvents.metadata}->>'companyId' in (${sql.join(companyIds.map(id=>sql`${id}`),sql`,`)})`,inArray(auditEvents.entityId,[...companyIds,...(batchId?[batchId]:[]),...(campaignId?[campaignId]:[])])));await db.delete(opportunities).where(inArray(opportunities.companyId,companyIds));await db.delete(contacts).where(inArray(contacts.companyId,companyIds));await db.delete(companies).where(inArray(companies.id,companyIds));}if(campaignId)await db.delete(campaigns).where(eq(campaigns.id,campaignId));await pool.end();});
