import Link from "next/link";
import { notFound } from "next/navigation";
import { eq } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import { companies,campaigns } from "@/db/schema";
import { requireUser } from "@/lib/auth";
import { canWrite } from "@/lib/security";
import { stageLabels } from "@/lib/outreach/contracts";
import { listCompanySales } from "@/lib/outreach/service";
import { ApiForm } from "@/components/forms";
export default async function CompanyOutreach({params}:{params:Promise<{id:string}>}){
  const user=await requireUser(),{id}=await params;if(!z.uuid().safeParse(id).success)notFound();const company=await db.query.companies.findFirst({where:eq(companies.id,id)});if(!company)notFound();
  const [sales,campaignRows]=await Promise.all([listCompanySales(id),db.select().from(campaigns).orderBy(campaigns.name)]);const write=canWrite(user.role);const eligible=sales.contacts.filter(c=>!c.doNotContactAt);
  return <><Link href={`/companies/${id}`}>← Pesquisa da empresa</Link><p className="eyebrow">RELACIONAMENTO COMERCIAL</p><h1>{company.displayName}</h1><p>Cadastre o contato profissional e vincule uma oportunidade a uma campanha. O contato é escolhido pelo operador; cargo não comprova poder de decisão.</p>
    <section className="panel"><h2>Contatos</h2>{!sales.contacts.length&&<p>Nenhum contato registrado.</p>}{sales.contacts.map(c=><article className="evidence-card" key={c.id}><h3>{c.name} · {c.title}</h3>{write&&<Link href={`/contacts/${c.id}`}>Editar cadastro →</Link>}<p>{c.doNotContactAt?<strong className="error">Opt-out: não contatar</strong>:c.contactStatus==="contacted"?"Contato manual confirmado":"Sem envio confirmado"}</p>{c.professionalUrl&&<a href={c.professionalUrl} target="_blank" rel="noopener noreferrer">Abrir perfil profissional ↗</a>}<p><a href={c.sourceUrl} target="_blank" rel="noopener noreferrer">Fonte ↗</a> · Cadastrado em {c.createdAt.toLocaleDateString("pt-BR",{timeZone:"UTC"})}</p><p>Finalidade: {c.purpose}</p>{write&&!c.doNotContactAt&&<details><summary>Registrar pedido de não contato</summary><p>Bloqueia novas abordagens, descarta rascunhos não enviados e cancela tarefas pendentes. O histórico de envios já confirmados é preservado.</p><ApiForm endpoint={`contacts/${c.id}/opt-out`} label="Registrar opt-out"><label className="checkbox"><input type="checkbox" name="confirmation" value="do_not_contact" required/>Confirmo o pedido de não contato desta pessoa.</label></ApiForm></details>}</article>)}</section>
    {write&&<section className="panel"><h2>Cadastrar contato profissional</h2><ApiForm endpoint={`companies/${id}/contacts`} label="Salvar contato"><div className="fields"><label>Nome<input name="name" required minLength={2} maxLength={160}/></label><label>Cargo informado<input name="title" required minLength={2} maxLength={160}/></label><label>Papel provável<select name="roleCategory"><option value="owner">Sócio(a)</option><option value="management">Direção</option><option value="administration">Administrativo / financeiro</option><option value="technical">Responsável técnico</option><option value="other">Outro / a confirmar</option></select></label><label>URL profissional (opcional)<input name="professionalUrl" type="url" maxLength={2000} placeholder="https://www.linkedin.com/in/…"/></label><label>E-mail de trabalho (opcional)<input name="workEmail" type="email" maxLength={254}/></label><label>URL da fonte<input name="sourceUrl" type="url" required maxLength={2000}/></label></div><label>Permissão de uso verificada<textarea name="permittedBasis" required minLength={10} maxLength={1000} rows={2}/></label><label>Finalidade profissional<textarea name="purpose" required minLength={10} maxLength={500} rows={2} defaultValue="Contato profissional para entender o processo de avaliação de mensagens suspeitas."/></label></ApiForm></section>}
    <section className="panel"><h2>Oportunidades</h2>{sales.opportunities.map(o=><p key={o.id}><Link href={`/opportunities/${o.id}`}>{campaignRows.find(c=>c.id===o.campaignId)?.name??"Campanha"} · {stageLabels[o.stage]??o.stage} →</Link></p>)}{!sales.opportunities.length&&<p>Nenhuma oportunidade cadastrada.</p>}{write&&eligible.length>0&&campaignRows.length>0&&<details open={!sales.opportunities.length}><summary>Nova oportunidade</summary><ApiForm endpoint="opportunities" label="Criar oportunidade"><input type="hidden" name="companyId" value={id}/><div className="fields"><label>Campanha<select name="campaignId" required>{campaignRows.map(c=><option key={c.id} value={c.id}>{c.name}</option>)}</select></label><label>Contato principal<select name="primaryContactId" required>{eligible.map(c=><option key={c.id} value={c.id}>{c.name} · {c.title}</option>)}</select></label></div></ApiForm></details>}{write&&!eligible.length&&<p>Cadastre um contato sem opt-out para criar uma oportunidade.</p>}</section>
  </>;
}
