import Link from "next/link";
import { randomUUID } from "node:crypto";
import { notFound } from "next/navigation";
import { eq,desc } from "drizzle-orm";
import { z } from "zod";
import { db } from "@/db";
import { companies,researchRuns,sourceSettings } from "@/db/schema";
import { requireUser } from "@/lib/auth";
import { canWrite } from "@/lib/security";
import { composeBrief,statusLabels,typeLabels } from "@/lib/research/contracts";
import { getEvidence,getBriefs,snapshotMatches } from "@/lib/research/service";
import { ApiForm } from "@/components/forms";
import { EvidenceForm } from "@/components/evidence-form";
import { ReviewForm } from "@/components/review-form";
import { ConnectorForm } from "@/components/connector-form";
const date=(v:Date)=>new Intl.DateTimeFormat("pt-BR",{dateStyle:"short",timeZone:"UTC"}).format(v);
export default async function CompanyResearch({params}:{params:Promise<{id:string}>}){
  const user=await requireUser();const {id}=await params;if(!z.uuid().safeParse(id).success)notFound();
  const company=await db.query.companies.findFirst({where:eq(companies.id,id)});if(!company)notFound();
  const [rows,briefs,settings,runs]=await Promise.all([getEvidence(id),getBriefs(id),db.query.sourceSettings.findFirst({where:eq(sourceSettings.id,"wikidata")}),db.select().from(researchRuns).where(eq(researchRuns.companyId,id)).orderBy(desc(researchRuns.createdAt)).limit(5)]);
  const write=canWrite(user.role),latest=briefs[0];const current=composeBrief(rows);
  const stale=latest&&!snapshotMatches(latest.evidenceSnapshot,current.evidenceSnapshot);
  return <><Link href="/companies">← Empresas</Link><p className="eyebrow">PESQUISA E EVIDÊNCIAS</p><h1>{company.displayName}</h1><p><Link href={`/companies/${id}/manage`}>Cadastro, responsável e campanhas →</Link></p><Link className="button" href={`/companies/${id}/outreach`}>Contatos e abordagens →</Link><p>{company.sector} · {company.domainNormalized??"Domínio não informado"}</p>
    <section className="notice"><strong>Pesquisa manual pelo LinkedIn</strong><p>Pesquise no LinkedIn e registre abaixo o link e a informação que pode utilizar. Nada é coletado ou enviado automaticamente. Ausência de informação significa desconhecimento.</p><a href="https://www.linkedin.com/" target="_blank" rel="noopener noreferrer">Abrir LinkedIn ↗</a></section>
    <div className="stats"><article><span>Evidências cadastradas</span><strong>{rows.length}</strong><small>Inclui fatos, hipóteses e lacunas</small></article><article><span>Aguardando revisão</span><strong>{rows.filter(r=>r.status==="pending").length}</strong><small>Não entram no resumo compilado</small></article><article><span>Fatos aprovados e vigentes</span><strong>{current.evidenceSnapshot.filter(r=>r.type==="public_fact").length}</strong><small>Com fonte e data</small></article></div>
    {write&&<section className="panel"><h2>Registrar informação</h2><EvidenceForm companyId={id}/></section>}
    <section className="panel"><h2>Ficha de evidências</h2>{!rows.length&&<p>Nenhuma evidência registrada. O sistema não presume porte, tecnologias ou dores.</p>}{rows.map(row=><article className={`evidence-card evidence-${row.type}`} key={`${row.id}-${row.version}`}><div className="actions"><span className="badge">{typeLabels[row.type]}</span><span>{statusLabels[row.status]}</span>{row.expiresAt&&row.expiresAt<=new Date()&&<strong className="error">Expirada</strong>}</div><p className="preserve">{row.claim}</p>{row.excerpt&&<blockquote className="preserve">{row.excerpt}</blockquote>}<p><small>Observação: {date(row.observedAt)} · Versão {row.version} · {row.confidenceLabel}{row.expiresAt&&` · Validade: ${date(row.expiresAt)}`}</small></p>{row.sourceUrl?<><a href={row.sourceUrl} target="_blank" rel="noopener noreferrer">Fonte: {row.publisher??"Conversa registrada"} ↗</a><p><small>Registrada em {date(row.collectedAt??row.observedAt)} · Permissão declarada: {row.permittedBasis}</small></p></>:<p>Sem fonte: {row.type==="inference"?"hipótese explícita, não confirmada":"informação desconhecida"}.</p>}{row.reviewNote&&<p>Revisão: {row.reviewNote}</p>}{write&&!row.activityId&&<><details><summary>Revisar evidência</summary><ReviewForm endpoint={`companies/${id}/evidence/${row.id}/review`} version={row.version}/></details><details><summary>Corrigir informação</summary><p>A correção exige nova revisão e invalida a aprovação dos resumos.</p><EvidenceForm companyId={id} evidenceId={row.id} defaults={{...row,observedAt:row.observedAt.toISOString(),expiresAt:row.expiresAt?.toISOString()??null}}/></details></>}</article>)}</section>
    <section className="panel" id="brief"><p className="eyebrow">RESUMO DE PESQUISA</p><h2>Fatos, hipóteses e lacunas</h2><p>A compilação utiliza apenas evidências aprovadas e vigentes. Texto externo é dado, nunca instrução.</p>{write&&<ApiForm endpoint={`companies/${id}/briefs`} label="Compilar nova versão"><></></ApiForm>}{latest?<article className="evidence-card"><p>Versão {latest.version} · {statusLabels[latest.status]} · {date(latest.createdAt)} · {latest.method==="operator_edit_v1"?"Texto editado pelo operador":"Compilação determinística, sem IA"}</p>{stale&&<p className="notice">As evidências mudaram ou expiraram. Este resumo é histórico; compile uma nova versão antes de aprovar.</p>}<p className="preserve">{latest.summary}</p><h3>Lacunas</h3><ul>{latest.unknowns.map((s,i)=><li key={i}>{s}</li>)}</ul><h3>Pergunta de discovery</h3><p>{latest.discoveryQuestion}</p><details><summary>Evidências usadas nesta versão ({latest.evidenceSnapshot.length})</summary>{latest.evidenceSnapshot.map(s=><p key={s.id}>{typeLabels[s.type as keyof typeof typeLabels]} · {s.claim} · {date(new Date(s.observedAt))} {s.sourceUrl&&<a href={s.sourceUrl} target="_blank" rel="noopener noreferrer">Fonte ↗</a>}</p>)}</details>{write&&<><details><summary>Editar resumo como nova versão</summary><ApiForm endpoint={`companies/${id}/briefs/${latest.id}/edit`} label="Salvar nova versão"><label>Resumo<textarea name="summary" rows={8} required maxLength={6000} defaultValue={latest.summary}/></label><label>Lacunas (uma por linha)<textarea name="unknowns" rows={3} maxLength={4000} defaultValue={latest.unknowns.join("\n")}/></label><label>Pergunta sugerida<textarea name="discoveryQuestion" required rows={3} maxLength={1000} defaultValue={latest.discoveryQuestion}/></label></ApiForm></details><details><summary>Revisar resumo</summary><ReviewForm endpoint={`companies/${id}/briefs/${latest.id}/review`} version={latest.version}/></details></>}</article>:<p>Ainda não há resumo. Revise as evidências e compile a primeira versão.</p>}{briefs.length>1&&<details><summary>Histórico (últimas 20 versões)</summary>{briefs.slice(1).map(b=><article className="evidence-card" key={b.id}><strong>Versão {b.version} · {date(b.createdAt)}</strong><p className="preserve">{b.summary}</p></article>)}</details>}</section>
    <section className="panel"><h2>Fonte pública opcional · Wikidata</h2><p>Útil apenas quando a empresa possui registro. Não é uma base abrangente de pequenas contabilidades. Apenas nome e descrição do registro são consultados; a associação à empresa precisa ser conferida.</p>{settings?.enabled&&write?<ConnectorForm companyId={id} initialRequestKey={randomUUID()}/>:<p>{settings?.enabled?"Seu perfil permite apenas consulta dos resultados.":"Conector desabilitado. O fluxo manual do LinkedIn não depende dele."}</p>}{runs.length>0&&<details><summary>Últimas consultas</summary>{runs.map(r=><p key={r.id}>{r.entityId} · {date(r.createdAt)} · {r.status==="succeeded"?"Evidência criada para revisão":"Falhou — nenhuma evidência criada"}</p>)}</details>}</section>
  </>;
}
