import Link from "next/link";
import { randomUUID } from "node:crypto";
import { notFound } from "next/navigation";
import { z } from "zod";
import { requireUser } from "@/lib/auth";
import { canWrite } from "@/lib/security";
import { stageLabels } from "@/lib/outreach/contracts";
import { getConversation } from "@/lib/conversations/service";
import { getEvidence } from "@/lib/research/service";
import { openAIConfig } from "@/lib/conversations/openai";
import { certaintyLabels,insightLabels } from "@/lib/conversations/contracts";
import { statusLabels } from "@/lib/research/contracts";
import { ConversationEntry } from "@/components/conversation-entry";
import { InsightReview } from "@/components/insight-review";
import { InsightFields } from "@/components/insight-fields";
import { ApiForm } from "@/components/forms";
export default async function ConversationPage({params}:{params:Promise<{id:string}>}){
  const user=await requireUser(),{id}=await params;if(!z.uuid().safeParse(id).success)notFound();let data;try{data=await getConversation(id);}catch{notFound();}
  const hypotheses=(await getEvidence(data.opportunity.companyId)).filter(e=>e.type==="inference"),write=canWrite(user.role),aiReady=!!openAIConfig();
  return <><Link href={`/opportunities/${id}`}>← Oportunidade</Link><p className="eyebrow">MEMÓRIA DE CONVERSA</p><h1>Respostas que viram contexto.</h1><p>Registre interações autorizadas. Cada interpretação fica ligada à mensagem original e exige revisão.</p>
    <section className="notice"><strong>Próxima ação sugerida: {data.nextAction.action}</strong><p>{data.nextAction.reason}</p><p>{data.nextAction.uncertainties.join(" ")} Nenhuma ação será executada automaticamente.</p>{data.nextAction.insight_ids.map(insightId=><p key={insightId}><a href={`#insight-${insightId}`}>Ver interpretação de apoio ↓</a></p>)}<Link href={`/companies/${data.opportunity.companyId}/outreach`}>Conferir contatos / registrar opt-out →</Link></section>
    {write&&<section className="panel"><h2>Registrar interação</h2><ConversationEntry opportunityId={id} contacts={data.contacts.map(c=>({id:c.id,name:c.name}))} initialKey={randomUUID()}/></section>}
    <section className="panel"><h2>Histórico de conversas</h2>{!data.messages.length&&<p>Nenhuma conversa registrada.</p>}{data.messages.map(a=><article key={`${a.id}-${a.version}`} id={`activity-${a.id}`} className="evidence-card"><h3>{data.contacts.find(c=>c.id===a.contactId)?.name} · {a.authorRole==="contact"?"Mensagem recebida":"Nota do operador"}</h3><p>{a.channel} · {a.happenedAt.toLocaleString("pt-BR",{timeZone:"UTC"})} UTC · versão {a.version}</p>{a.deletedAt?<p>Conteúdo apagado pelo operador; registro mínimo da atividade preservado.</p>:<><blockquote className="preserve">{a.body}</blockquote><p><small>Permissão registrada: {a.permittedBasis}</small></p>{write&&<>{a.authorRole==="contact"&&<><details><summary>Analisar mensagem</summary><p>A análise local identifica palavras-chave e pode errar contexto e negação. A OpenAI é opcional e permanece desativada até configuração.</p><ApiForm endpoint={`activities/${a.id}/extract-insights`} label="Extrair sugestões para revisar"><input type="hidden" name="version" value={a.version}/><label>Método<select name="method"><option value="local">Regras locais — sem IA e sem envio externo</option><option value="openai" disabled={!aiReady}>OpenAI {aiReady?"(configurada)":"(não configurada)"}</option></select></label>{aiReady&&<label className="checkbox"><input type="checkbox" name="authorization" value="authorize_openai"/>Se selecionar OpenAI, autorizo o envio deste texto revisado ao provedor para esta análise.</label>}<label>Tentativa<select name="retry"><option value="false">Usar resultado existente, se houver</option><option value="true">Repetir somente se a última análise falhou</option></select></label></ApiForm>{data.runs.filter(r=>r.activityId===a.id&&r.activityVersion===a.version).map(r=><p key={r.id}>{r.method.startsWith("openai:")?"OpenAI":"Regras locais"} · {r.status==="succeeded"?`${r.candidateCount} sugestões retornadas`:"Falha; nenhuma sugestão aplicada"} · {r.attempts} tentativa(s)</p>)}</details><details><summary>Registrar insight manualmente</summary><ApiForm endpoint={`activities/${a.id}/insights`} label="Salvar insight para revisão"><input type="hidden" name="activityVersion" value={a.version}/><InsightFields/></ApiForm></details></>}
    <details><summary>Corrigir texto registrado</summary><p>Remove interpretações e declarações derivadas desta mensagem e resumos que as utilizaram. Hipóteses afetadas voltam à revisão quando ainda estão na versão vinculada.</p><ApiForm endpoint={`activities/${a.id}/edit`} label="Salvar correção"><input type="hidden" name="version" value={a.version}/><label>Texto revisado<textarea name="body" rows={5} defaultValue={a.body??""} maxLength={8000} minLength={3} required/></label><label className="checkbox"><input type="checkbox" name="confirmation" value="authorized_and_redacted" required/>Revisei o conteúdo e a remoção de dados sensíveis.</label></ApiForm></details><details><summary>Apagar conteúdo da conversa</summary><p>Remove o texto, insights, declarações derivadas e resumos que as utilizaram. O evento mínimo de registro permanece.</p><ApiForm endpoint={`activities/${a.id}/erase`} label="Apagar conteúdo e derivações"><input type="hidden" name="version" value={a.version}/><label className="checkbox"><input type="checkbox" name="confirmation" value="erase_content" required/>Confirmo apagar este conteúdo e suas derivações.</label></ApiForm></details></>}</>}</article>)}</section>
    <section className="panel"><h2>Interpretações para revisar</h2>{!data.insights.length&&<p>Nenhuma interpretação registrada.</p>}{data.insights.map(i=><article className="evidence-card" id={`insight-${i.id}`} key={`${i.id}-${i.version}`}><span className="badge">{insightLabels[i.kind as keyof typeof insightLabels]}</span><h3>{i.normalizedLabel}</h3><blockquote className="preserve">{i.rawExcerpt}</blockquote><p>{certaintyLabels[i.certainty as keyof typeof certaintyLabels]} · {statusLabels[i.status]} · {i.method==="manual"?"Registro manual":i.method.startsWith("openai:")?"Sugestão OpenAI":"Sugestão por palavras-chave, sem IA"}</p><a href={`#activity-${i.activityId}`}>Ver mensagem de origem ↑</a>{i.reviewNote&&<p>Revisão: {i.reviewNote}</p>}{i.publishedEvidenceId&&<p><Link href={`/companies/${data.opportunity.companyId}`}>Declaração revisada publicada na ficha →</Link></p>}{i.kind==="opt_out"&&<p className="notice">Revise o pedido e registre o opt-out na ficha do contato. Esta interpretação não executa bloqueio automaticamente.</p>}{write&&<><details><summary>Revisar interpretação</summary><InsightReview id={i.id} version={i.version} canContradict={i.kind==="contradiction"&&i.certainty==="explicit"&&i.status!=="approved"} targets={hypotheses}/></details>{i.status!=="approved"&&<details><summary>Editar interpretação</summary><ApiForm endpoint={`conversation-insights/${i.id}/edit`} label="Salvar interpretação corrigida"><input type="hidden" name="version" value={i.version}/><InsightFields defaults={i}/></ApiForm></details>}</>}</article>)}</section>
    {write&&<section className="panel"><h2>Registrar evolução da oportunidade</h2><p>Salvar conversa ou extrair insights não altera o pipeline. Mudanças abaixo exigem decisão explícita.</p><p>Estágio atual: {stageLabels[data.opportunity.stage]??data.opportunity.stage}{data.opportunity.lostReason&&` · Motivo de perda: ${data.opportunity.lostReason}`}</p><ApiForm endpoint={`opportunities/${id}/conversation-stage`} label="Registrar estágio revisado"><input type="hidden" name="version" value={data.opportunity.stageVersion}/><label>Novo estágio<select name="stage"><option value="replied">Resposta recebida</option><option value="discovery">Discovery</option><option value="meeting">Reunião</option><option value="trial">Teste do produto</option><option value="negotiation">Negociação</option><option value="follow_up_later">Acompanhar depois</option><option value="no_response">Sem resposta</option><option value="lost">Perdida</option></select></label><label>Motivo (obrigatório; revisável)<textarea name="reason" rows={2} minLength={5} maxLength={1000} required/></label><label className="checkbox"><input type="checkbox" name="confirmation" value="reviewed_stage" required/>Conferi o estágio e o motivo; esta é minha decisão.</label></ApiForm></section>}
  </>;
}
